[workspace]
resolver = "2"
members = [
  "crates/raceline-optimizer",
  "crates/raceline-optimizer-cli",
]

[workspace.package]
edition = "2021"
rust-version = "1.85"
authors = ["RedRatInHat"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/RedRatInHat/global_racetrajectory_optimization"
homepage = "https://redratinhat.com/products/racelinecalc/"
